# -*- coding: utf-8 -*-
"""07.10.24 "ДЗ Pro | Нейро-копирайтер по видео | УИИ.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0IKlCjBQ1EpfCrmigZgIrAglLa3N0e6

Возьмите видео с ютуб, аудио-файл и текстовый документ по ссылкам, транскрибируйте видео и аудио -дорожку, полученные тексты соедините с текстовым документом, на основе получившегося текста создайте нейро-консультанта для ответов на вопросы по данным материалам, а также краткую методичку.

Видео: https://youtu.be/LRuszWRN4uI?si=dITP2gIzRaVuec8- Python в вопросах и ответах

Аудио: https://drive.google.com/file/d/1TLsB8EEMqATs18Iwacw5H3nceOFeO7ND/view?usp=sharing ООП в Пайтон

Текст: https://docs.google.com/document/d/1GwrAY4NoqPImiSMola-14ykVB5K-8iDlivWzvuEnMfA/edit?usp=sharing Объяснение алгоритмов сортировки с примерами на Python

P.S. аудио-файлы для обработки whisper стоит сохранить с именем на латинице и без пробелов в названии.
"""

!pip -q install yt-dlp -U # Устанавливаем библиотеку для загрузки звука с видео. документация https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#readme
!pip install git+https://github.com/openai/whisper.git

!pip install tiktoken==0.4.0 openai==0.28.0 langchain==0.0.281 faiss-cpu==1.7.4
!pip install --no-cache-dir gdown
!pip install -qq python-docx
!pip install -U pytube
from IPython.display import clear_output
clear_output()

import whisper
import os
import gdown
import requests
import re
import time
from IPython.display import HTML, clear_output
import subprocess
from pathlib import Path
import json
from pytube import YouTube
import tiktoken
from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
import ipywidgets as widgets
from IPython.display import display
from tqdm.auto import tqdm
import getpass
import pickle
from urllib.request import urlopen
import openai
import subprocess
import codecs
from langchain.chains import ConversationChain         # Импортируем класс для создания цепочек диалогов
from langchain.chat_models import ChatOpenAI           # Импортируем класс для работы с чатами на базе OpenAI
from langchain.llms import OpenAI
from langchain.memory import ConversationBufferMemory  # Импортируем класс для управления памятью диалогов
from langchain.text_splitter import MarkdownHeaderTextSplitter, Document, RecursiveCharacterTextSplitter
from langchain.schema import (
    AIMessage,
    HumanMessage,
    SystemMessage
)
import urllib

"""Получаем аудио-дорожку из видео по ссылке на видео ролик."""

import yt_dlp

# Ссылка на видео
URLS = ['https://youtu.be/LRuszWRN4uI']  # Указываем ссылку для получения аудио-дорожки из видео

# Придумаем короткое имя для сохраняемого аудио файла на английском языке
name = 'My_Audio'

output_template = f'{name}.m4a'

# Опции для получения лучшего качества звука
ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'm4a',
    }],
    'outtmpl': output_template,
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    error_code = ydl.download(URLS)
    if error_code == 0:
        print('Загрузка файла прошла успешно!')
    else:
        print(f'Код ошибки: {error_code}')

print(f"\nАудиофайл загружен, путь до файла: {output_template}")

import gdown

# ID файла на Google Drive
file_id = '1TLsB8EEMqATs18Iwacw5H3nceOFeO7ND'

# Формируем прямую ссылку для gdown
gdrive_url = f'https://drive.google.com/uc?id={file_id}'

# Имя для сохранения файла (на латинице и без пробелов)
audio_file_name = 'oop_python_audio.mp3'

# Скачиваем файл
gdown.download(gdrive_url, audio_file_name, quiet=False)

import openai
import os
import getpass

openai.api_key = getpass.getpass('Введите ваш OpenAI API ключ: ')
os.environ["OPENAI_API_KEY"] = openai.api_key

!whisper '{output_template}' --model large --language Russian --output_format txt

!whisper '{audio_file_name}' --model large --language Russian --output_format txt

import os

# Сначала проверим, создался ли файл после распознавания
output_template = 'My_Audio.m4a.m4a'  # Предполагаем, что это исходное имя файла

# Проверьте, существует ли файл My_Audio.txt после выполнения команды whisper
if not os.path.exists('handbook.txt'):
    print(f"Файл 'My_Audio.txt' не найден. Проверьте, был ли успешно выполнен процесс транскрибации.")
else:
    # Текст из видео
    with open('handbook.txt', 'r', encoding='utf-8') as f:
        video_text = f.read()

    # Текст из аудио-файла
    with open('oop_python_audio.txt', 'r', encoding='utf-8') as f:
        audio_text = f.read()

    # Текст из документа
    with open('oop_python_audio.txt', 'r', encoding='utf-8') as f:
        document_text = f.read()

    combined_text = video_text + '\n\n' + audio_text + '\n\n' + document_text

    # Дальнейшая обработка текста...
    print("Все файлы прочитаны успешно.")

combined_text = video_text + '\n\n' + audio_text + '\n\n' + document_text

from langchain.text_splitter import RecursiveCharacterTextSplitter, Document
from IPython.display import display, HTML

def set_text_wrap_css():
    css = '''
    <style>
    pre {
        white-space: pre-wrap;
    }
    </style>
    '''
    display(HTML(css))

get_ipython().events.register('pre_run_cell', set_text_wrap_css)

def split_text(text, chunk_size=5000):
    source_chunks = []
    splitter = RecursiveCharacterTextSplitter(separators=['\n', '\n\n', '. '], chunk_size=chunk_size, chunk_overlap=0)
    for chunk in splitter.split_text(text):
        source_chunks.append(Document(page_content=chunk, metadata={}))
    print(f'\n\nТекст разбит на {len(source_chunks)} чанков.')
    return source_chunks

def answer_index(system, user, chunk, temp=0, model='gpt-3.5-turbo'):
    messages = [
        {'role': 'system', 'content': system},
        {'role': 'user', 'content': user + f'\n\n{chunk}'}
    ]
    completion = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temp
    )
    answer = completion.choices[0].message.content
    return answer

def process_text(text, system, user):
    source_chunks = split_text(text)
    processed_text = ''
    for chunk in source_chunks:
        attempt = 0
        while attempt < 3:
            try:
                answer = answer_index(system, user, chunk.page_content)
                break
            except Exception as e:
                attempt += 1
                print(f'\n\nПопытка {attempt} не удалась из-за ошибки: {str(e)}')
                time.sleep(10)
                if attempt == 3:
                    answer = ''
                    print(f'\n\nОбработка элемента не удалась после 3 попыток')
        processed_text += f'{answer}\n\n'
        print(f'{answer}')
    return processed_text

system = "Вы являетесь экспертом-писателем и редактором. Ваша задача — распознать логические разделы в предоставленном тексте и разделить его соответственно, сохраняя 100% оригинального содержимого."

user = "Пожалуйста, подумайте шаг за шагом: определите разделы в тексте и присвойте каждому осмысленное название. Затем напишите свой ответ в следующем формате: ## Название раздела, затем весь текст, относящийся к этому разделу. Текст:"

processed_text = process_text(combined_text, system, user)

from langchain.text_splitter import MarkdownHeaderTextSplitter

headers_to_split_on = [
    ("##", "Header 2")
]

markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
md_header_splits = markdown_splitter.split_text(processed_text)

for document in md_header_splits:
    header = document.metadata['Header 2']
    document.page_content = f'{header}. {document.page_content}'

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS

embeddings = OpenAIEmbeddings()
db = FAISS.from_documents(md_header_splits, embeddings)

system_for_NA = "Ты — опытный преподаватель по программированию на Python. Твоя задача — отвечать на вопросы студентов, используя только предоставленную информацию из документов. Отвечай на русском языке. Не добавляй ничего от себя."

import re

def answer_neuro_assist(system_for_NA, topic, search_index, verbose=1):
    docs = search_index.similarity_search(topic, k=3)
    if verbose:
        print('\n ===========================================: ')
    message_content = re.sub(r'\n{2,}', ' ', '\n '.join([f'\nОтрывок документа №{i+1}\n=====================' + doc.page_content + '\n' for i, doc in enumerate(docs)]))
    if verbose:
        print('message_content :\n ======================================== \n', message_content)
    messages = [
        {"role": "system", "content": system_for_NA},
        {"role": "user", "content": f"Ответь на вопрос студента. Не упоминай отрывки документов в ответе. Документ с информацией для ответа студенту: {message_content}\n\nВопрос студента:\n{topic}"}
    ]
    if verbose:
        print('\n ===========================================: ')
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages,
        temperature=0
    )
    answer = completion.choices[0].message.content
    return answer

# Примеры вопросов
questions = [
    "Что такое ООП в Python и какие его основные концепции?",
    "Как работает алгоритм быстрой сортировки в Python?",
    "Объясните принцип наследования в ООП на Python."
]

for question in questions:
    ans = answer_neuro_assist(system_for_NA, question, db, verbose=0)
    print(f"Вопрос: {question}\nОтвет: {ans}\n")

system = "Вы — гениальный копирайтер и эксперт в программировании на Python. Вы получаете раздел необработанного текста по определенной теме. Вам нужно выделить только самую суть, сохранив все необходимые детали, но убрав всю ненужную информацию."

user = "Из данного текста выделите только ценную информацию по теме 'Программирование на Python'. Удалите всю 'воду'. В результате у вас должен получиться раздел для методички по данной теме. Опирайтесь только на предоставленный текст, не добавляйте ничего от себя. Ответ должен быть в формате: ## Название раздела, затем ценная информация. Если в тексте нет ценной информации, оставьте только название раздела, например: '## Введение'. Текст:"

def process_documents(documents, system, user, temperature=0):
    processed_text_for_handbook = ""
    for document in documents:
        answer = answer_index(system, user, document.page_content, temperature, model='gpt-3.5-turbo')
        processed_text_for_handbook += f"{answer}\n\n"
    with open('handbook.txt', 'w', encoding='utf-8') as f:
        f.write(processed_text_for_handbook)
    return 'handbook.txt'

handbook_file_path = process_documents(md_header_splits, system, user)
print(f"Методичка сохранена в файле: {handbook_file_path}")

with open(handbook_file_path, 'r', encoding='utf-8') as f:
    handbook_content = f.read()

print(handbook_content)